version: '3.7'
services:
  dnsdist:
    build: .
    ports:
      - "8053:8053"
      - "53:53/udp"
      - "53:53/tcp"
    tty: true
    networks:
      dnsnet:
  unbound:
    image: mvance/unbound:latest
    networks:
      dnsnet:
        ipv4_address: 10.152.118.100

networks:
  dnsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.152.118.0/24
